apiVersion: batch/v1
kind: Job
metadata:
  name: master-backend-migrator-job
  labels:
    app: master-backend-migrator
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: master-backend-migrator
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: marketplace-regcred
      containers:
        - name: migrator
          image: gitlab.infocraft.ru:5050/experiments/marketplace1/migrator:<VERSION>
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: master-backend-config
            - secretRef:
                name: master-backend-secrets
