CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "ClientNotifications" (
    "Id" uuid NOT NULL,
    "TicketId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RelatedEntityId" uuid,
    "RelatedEntityType" text,
    CONSTRAINT "PK_ClientNotifications" PRIMARY KEY ("Id")
);

CREATE TABLE "MasterNotifications" (
    "Id" uuid NOT NULL,
    "MasterId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RelatedEntityId" uuid,
    "RelatedEntityType" text,
    CONSTRAINT "PK_MasterNotifications" PRIMARY KEY ("Id")
);

CREATE TABLE "Organizations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "INN" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
);

CREATE TABLE "Services" (
    "Id" uuid NOT NULL,
    "OrgId" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Price" double precision NOT NULL,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
);

CREATE TABLE "OrganizationDispatchers" (
    "UserId" uuid NOT NULL,
    "OrgId" integer NOT NULL,
    CONSTRAINT "PK_OrganizationDispatchers" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_OrganizationDispatchers_Organizations_OrgId" FOREIGN KEY ("OrgId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrganizationMasters" (
    "OrgId" integer NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_OrganizationMasters" PRIMARY KEY ("OrgId", "UserId"),
    CONSTRAINT "FK_OrganizationMasters_Organizations_OrgId" FOREIGN KEY ("OrgId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ServiceQuests" (
    "Id" uuid NOT NULL,
    "OrgId" integer NOT NULL,
    "MasterId" uuid NOT NULL,
    "ServiceId" uuid NOT NULL,
    "Number" integer NOT NULL,
    "Status" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Deadline" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "FinishedAt" timestamp with time zone,
    "ScheduledStartDate" timestamp with time zone,
    "ScheduledEndDate" timestamp with time zone,
    "Address" text NOT NULL,
    "AccountNumber" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "ClientName" text NOT NULL,
    "ClientComment" text NOT NULL,
    "FixedPrice" double precision NOT NULL,
    "SpentTimeHours" double precision,
    "CompletionComment" text,
    "RelatedTicketId" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_ServiceQuests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ServiceQuests_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ServiceQuestAttachments" (
    "Id" uuid NOT NULL,
    "ServiceQuestId" uuid NOT NULL,
    "FileId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ServiceQuestAttachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ServiceQuestAttachments_ServiceQuests_ServiceQuestId" FOREIGN KEY ("ServiceQuestId") REFERENCES "ServiceQuests" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ServiceQuestStatusHistories" (
    "Id" uuid NOT NULL,
    "StatusRequestId" uuid NOT NULL,
    "ChangedAt" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "ChangedBy" integer NOT NULL,
    "Comment" text NOT NULL,
    CONSTRAINT "PK_ServiceQuestStatusHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ServiceQuestStatusHistories_ServiceQuests_StatusRequestId" FOREIGN KEY ("StatusRequestId") REFERENCES "ServiceQuests" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_OrganizationDispatchers_OrgId" ON "OrganizationDispatchers" ("OrgId");

CREATE INDEX "IX_ServiceQuestAttachments_ServiceQuestId" ON "ServiceQuestAttachments" ("ServiceQuestId");

CREATE INDEX "IX_ServiceQuests_ServiceId" ON "ServiceQuests" ("ServiceId");

CREATE INDEX "IX_ServiceQuestStatusHistories_StatusRequestId" ON "ServiceQuestStatusHistories" ("StatusRequestId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260611085258_InitialApp', '9.0.16');

COMMIT;

