apiVersion: v1
kind: Secret
metadata:
  name: master-backend-secrets
  labels:
    app: master-backend
type: Opaque
stringData:
  # Подключение к внешней БД
  ConnectionStrings__DefaultConnection: "Host=192.168.0.137;Port=5432;Database=master;Username=postgres;Password=spam2003"
  
  # Секретный ключ JWT (очень длинная строка)
  Jwt__SecretKey: "super_secret_key_which_is_very_long_for_hmac_sha256_at_least_32_bytes"
  
  # Доступы Minio
  Minio__AccessKey: "tTSEallGJquheqhpJx3k"
  Minio__SecretKey: "deEo4na2ODFftDiLjqTU1PcpXqe7x0rxR9qTrzas"
