apiVersion: v1
kind: Service
metadata:
  name: master-backend-service
  labels:
    app: master-backend
spec:
  # Используем NodePort для доступа снаружи
  type: LoadBalancer
  selector:
    app: master-backend
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8080
  externalIPs:
    - 192.168.0.234
      
